// Code generated by MockGen. DO NOT EDIT.
// Source: service/planetmint_client.go

// Package testutil is a generated GoMock package.
package testutil

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	types "github.com/planetmint/planetmint-go/x/dao/types"
)

// MockIPlanetmintClient is a mock of IPlanetmintClient interface.
type MockIPlanetmintClient struct {
	ctrl     *gomock.Controller
	recorder *MockIPlanetmintClientMockRecorder
}

// MockIPlanetmintClientMockRecorder is the mock recorder for MockIPlanetmintClient.
type MockIPlanetmintClientMockRecorder struct {
	mock *MockIPlanetmintClient
}

// NewMockIPlanetmintClient creates a new mock instance.
func NewMockIPlanetmintClient(ctrl *gomock.Controller) *MockIPlanetmintClient {
	mock := &MockIPlanetmintClient{ctrl: ctrl}
	mock.recorder = &MockIPlanetmintClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIPlanetmintClient) EXPECT() *MockIPlanetmintClientMockRecorder {
	return m.recorder
}

// CheckMintRequest mocks base method.
func (m *MockIPlanetmintClient) CheckMintRequest(txhash string) (*types.QueryGetMintRequestsByHashResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckMintRequest", txhash)
	ret0, _ := ret[0].(*types.QueryGetMintRequestsByHashResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckMintRequest indicates an expected call of CheckMintRequest.
func (mr *MockIPlanetmintClientMockRecorder) CheckMintRequest(txhash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckMintRequest", reflect.TypeOf((*MockIPlanetmintClient)(nil).CheckMintRequest), txhash)
}

// MintPLMNT mocks base method.
func (m *MockIPlanetmintClient) MintPLMNT(beneficiary string, amount uint64, liquidTxHash string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MintPLMNT", beneficiary, amount, liquidTxHash)
	ret0, _ := ret[0].(error)
	return ret0
}

// MintPLMNT indicates an expected call of MintPLMNT.
func (mr *MockIPlanetmintClientMockRecorder) MintPLMNT(beneficiary, amount, liquidTxHash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MintPLMNT", reflect.TypeOf((*MockIPlanetmintClient)(nil).MintPLMNT), beneficiary, amount, liquidTxHash)
}
