---
name: Audit

on: [push]

jobs:
  audit:
    strategy:
      matrix:
        directory: ['./', 'client']
    uses: rddl-network/github-actions/.github/workflows/audit.yaml@main
    with:
      working-directory: ${{ matrix.directory }}
